// Generated by Wrangler by running `wrangler types`

interface Env {
	SUPABASE_URL: "https://urpzmcvftooacnnwdpqn.supabase.co";
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").TalebElmMcp>;
}
